version: '3.8'

services:
  # 1. Tu aplicación de Astro compilada localmente
  astro-site:
    image: lyrics-web:latest
    container_name: lyrics-web 
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true 
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=4321

  # 2. El conector de Cloudflare que sacará tu app a internet
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: lyrics-tunnel 
    restart: always
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYzFjOTllMjg2NjFmYWRhYTE3MDYzMzM1YTc2YzdmMmUiLCJ0IjoiZWJmMmIyMWUtYjFmYi00YjdmLTk1MTMtZjMzMTk2MWIyYTE5IiwicyI6Ik1qVTRNRFV4TUdRdE9USmhNUzAwTlRneUxUZzNaR1F0WVRSaFlUZGhOVEZoWldJNE9HRTBZbVptTTJFdFpqRmtOeTAwWW1ZekxXRm1NMlF0TkRObU9XVTRaV0l5TTJFMCJ9
    command: tunnel --no-autoupdate run
    depends_on:
      - astro-site
